# https://travis-ci.org/christoph2/wiloplr
language: python
sudo: required
python:
    - 2.7.8
#    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - "pypy"

os:
  - linux
#  - osx

notifications:
  email: false
    slack: emberlin:UwtqxPbMBl2OJIVlIBFOtzY5

install:
  - pip install -r requirements.txt
  - travis_retry pip install pylint
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

script:
  coverage run --source=pywilo setup.py test

after_success:
  - pylint app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml

